// <auto-generated />
using System;
using LOTS3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace LOTS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210622174103_CreateDB")]
    partial class CreateDB
    {
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("Relational:MaxIdentifierLength", 128)
//                .HasAnnotation("ProductVersion", "5.0.7")
//                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//            modelBuilder.Entity("LOTS.Models.Coordinator", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("DepartmentAbrv")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int?>("DepartmentId")
//                        .HasColumnType("int");

//                    b.Property<string>("Division")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Email")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("EmployeeNo")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("FirstName")
//                        .IsRequired()
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.Property<string>("LastName")
//                        .IsRequired()
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.Property<string>("PhoneNumber")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.HasIndex("DepartmentId");

//                    b.ToTable("Coordinator");
//                });

//            modelBuilder.Entity("LOTS.Models.Department", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("DepartmentAbrv")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("DepartmentName")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("DepartmentNo")
//                        .HasColumnType("int");

//                    b.Property<int>("FundOrg")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.ToTable("Department");
//                });

//            modelBuilder.Entity("LOTS.Models.Lot", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("LotName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("LotNo")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.ToTable("Lot");
//                });

//            modelBuilder.Entity("LOTS.Models.Permit", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("Comments")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<DateTime?>("EndDate")
//                        .HasColumnType("datetime2");

//                    b.Property<int>("LotId")
//                        .HasColumnType("int");

//                    b.Property<int>("PermitTypeId")
//                        .HasColumnType("int");

//                    b.Property<int>("PermitteeId")
//                        .HasColumnType("int");

//                    b.Property<int>("PermitteeTypeId")
//                        .HasColumnType("int");

//                    b.Property<DateTime?>("StartDate")
//                        .HasColumnType("datetime2");

//                    b.HasKey("Id");

//                    b.HasIndex("LotId");

//                    b.HasIndex("PermitTypeId");

//                    b.HasIndex("PermitteeId");

//                    b.HasIndex("PermitteeTypeId");

//                    b.ToTable("Permit");
//                });

//            modelBuilder.Entity("LOTS.Models.PermitType", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("PermitTypeName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("PermitTypeNo")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.ToTable("PermitType");
//                });

//            modelBuilder.Entity("LOTS.Models.Permittee", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<int>("DepartmentId")
//                        .HasColumnType("int");

//                    b.Property<string>("Division")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("Email")
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("EmployeeNo")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<string>("FirstName")
//                        .IsRequired()
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.Property<string>("LastName")
//                        .IsRequired()
//                        .HasMaxLength(50)
//                        .HasColumnType("nvarchar(50)");

//                    b.Property<string>("PhoneNumber")
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.HasIndex("DepartmentId");

//                    b.ToTable("Permittee");
//                });

//            modelBuilder.Entity("LOTS.Models.PermitteeType", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("int")
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("PermitteeTypeName")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<int>("PermitteeTypeNo")
//                        .HasColumnType("int");

//                    b.HasKey("Id");

//                    b.ToTable("PermitteeType");
//                });

//            modelBuilder.Entity("LOTS.Models.Coordinator", b =>
//                {
//                    b.HasOne("LOTS.Models.Department", "Department")
//                        .WithMany()
//                        .HasForeignKey("DepartmentId")
//                        .OnDelete(DeleteBehavior.Restrict);

//                    b.Navigation("Department");
//                });

//            modelBuilder.Entity("LOTS.Models.Permit", b =>
//                {
//                    b.HasOne("LOTS.Models.Lot", "Lot")
//                        .WithMany("Permits")
//                        .HasForeignKey("LotId")
//                        .OnDelete(DeleteBehavior.Restrict)
//                        .IsRequired();

//                    b.HasOne("LOTS.Models.PermitType", "PermitType")
//                        .WithMany("Permits")
//                        .HasForeignKey("PermitTypeId")
//                        .OnDelete(DeleteBehavior.Restrict)
//                        .IsRequired();

//                    b.HasOne("LOTS.Models.Permittee", "Permittee")
//                        .WithMany("Permits")
//                        .HasForeignKey("PermitteeId")
//                        .OnDelete(DeleteBehavior.Restrict)
//                        .IsRequired();

//                    b.HasOne("LOTS.Models.PermitteeType", "PermitteeType")
//                        .WithMany("Permits")
//                        .HasForeignKey("PermitteeTypeId")
//                        .OnDelete(DeleteBehavior.Restrict)
//                        .IsRequired();

//                    b.Navigation("Lot");

//                    b.Navigation("Permittee");

//                    b.Navigation("PermitteeType");

//                    b.Navigation("PermitType");
//                });

//            modelBuilder.Entity("LOTS.Models.Permittee", b =>
//                {
//                    b.HasOne("LOTS.Models.Department", "Department")
//                        .WithMany()
//                        .HasForeignKey("DepartmentId")
//                        .OnDelete(DeleteBehavior.Restrict)
//                        .IsRequired();

//                    b.Navigation("Department");
//                });

//            modelBuilder.Entity("LOTS.Models.Lot", b =>
//                {
//                    b.Navigation("Permits");
//                });

//            modelBuilder.Entity("LOTS.Models.PermitType", b =>
//                {
//                    b.Navigation("Permits");
//                });

//            modelBuilder.Entity("LOTS.Models.Permittee", b =>
//                {
//                    b.Navigation("Permits");
//                });

//            modelBuilder.Entity("LOTS.Models.PermitteeType", b =>
//                {
//                    b.Navigation("Permits");
//                });
//#pragma warning restore 612, 618
//        }
    }
}
